# Generated by Django 5.1.1 on 2024-11-01 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    #operations = [
        #migrations.DeleteModel(
            #name='CustomUser',
        #),
    #]
