# Generated by Django 5.1.2 on 2024-10-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='delivery_method',
            field=models.CharField(choices=[('QR Code', 'QR Code'), ('Photo Validation', 'Photo Validation'), ('Integration', 'Integration')], default='QR Code', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
