# Generated by Django 5.1.1 on 2024-11-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reward_is_active_redeemedreward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemedreward',
            name='points_spent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
