# Generated by Django 5.1.1 on 2024-10-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_campaign_delivery_method_campaign_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='points',
            field=models.IntegerField(),
        ),
    ]
