# Generated by Django 5.1.2 on 2024-11-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_profile_delete_customuser"),
        ("main", "0003_alter_profile_graduation_year"),
    ]

    operations = []
