# Generated by Django 5.1.2 on 2024-11-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_merge_20241104_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='add_to_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
