# Generated by Django 5.1.2 on 2024-12-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_profile_major1_profile_major2_profile_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="major2",
            field=models.CharField(default="N/A", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="school",
            field=models.CharField(
                blank=True, default="Boston College", max_length=100, null=True
            ),
        ),
    ]
