# Generated by Django 5.1.2 on 2024-12-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_profile_major2_alter_profile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points_spent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
