# Generated by Django 5.1.2 on 2024-11-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_profile_graduation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='major1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
