# Generated by Django 5.1.2 on 2024-12-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_campaign_is_permanent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='points_spent',
        ),
    ]
