# Generated by Django 5.1.1 on 2024-11-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_profile_is_supervisor_remove_profile_major1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('points_required', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
