# Generated by Django 5.1.2 on 2024-12-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_profile_points_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points_spent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
