# Generated by Django 5.1.1 on 2024-11-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_reward_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
