# Generated by Django 5.1.1 on 2024-11-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_redeemedreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
